### ISSUE TITLE
case sensitivity

### ISSUE THREAD

**Issue by CeterisParibus51** [jhntrnr/word-shapes#4]
issue is explained in the #commented section, but i provided a bit of extra context for how i encountered it.

i made a fork trying to repurpose this for music notes rather than english, so far im running into an issue with two characters having one coordinate in the case of flats, ie Cb, Db, Eb, Gb, and Ab crash the program because of "b"

decided to tinker some more and try repurposing it for hex strings, ran into an issue, with capital letters,

# the issue
went back to the original version (ive kept yours in its own folder completely unedited), tried the word Test
it threw an issue with the capital T
the input field needs to auto lowercase the text input before graphing it.
# /the issue

#what terminal says: input was the word "Test"
Traceback (most recent call last):
  File "C:\Users\User\Desktop\word-shapes-main\word_explorer.py", line 109, in update_display_mode
    self.display_many_words([self.input_field.text().strip()])
  File "C:\Users\User\Desktop\word-shapes-main\word_explorer.py", line 187, in display_many_words
    polygon_shape = self.word_shape.get_polygon_shape(word)
  File "C:\Users\User\Desktop\word-shapes-main\word_shape.py", line 20, in get_polygon_shape
    return [self.letter_wheel.get_coordinates(letter, True) for letter in unique_letters]
  File "C:\Users\User\Desktop\word-shapes-main\word_shape.py", line 20, in <listcomp>
    return [self.letter_wheel.get_coordinates(letter, True) for letter in unique_letters]
  File "C:\Users\User\Desktop\word-shapes-main\letter_wheel.py", line 22, in get_coordinates
    return self.high_precision_letter_mapping[letter]
KeyError: 'T'

im working on some changes you might find interesting to expand this thing, and when ive got them up and running ill post them to a fork for you to check out

**Comment by CeterisParibus51** [comment]
im deleting my fork, swapping the music notes idea to just be base12 0,1,2,3,4,5,6,7,8,9,A,B instead, and going to attempt to port to tkinter/ttk instead because qt has some quite restrictive policies on use.
